services:
  web:
    image: thanhtunguet/ttdn:latest
    ports:
      - 3000:3000
    env_file:
      - .env
    networks:
      - ttdn
    volumes:
      - ./companies.log:/app/companies.log
    command: yarn start:prod
  crawler:
    image: thanhtunguet/ttdn:latest
    env_file:
      - .env.crawler
    networks:
      - ttdn
    depends_on:
      - web
    command: yarn start:crawler:prod
networks:
  ttdn:
    driver: bridge
